set -g default-terminal "tmux-256color"

set -g base-index 0
set -g pane-base-index 0

set -g status-keys vi
set -g mode-keys vi

set -g mouse on
set -g focus-events off
set -g aggressive-resize off
set -g clock-mode-style 12
set -s escape-time 500
set -g history-limit 20000

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

is_hx="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?hx?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_hx" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_hx" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_hx" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_hx" 'send-keys C-l'  'select-pane -R'
